name: lines-of-action
version: '0.0.0'
github: "jxv/lines-of-action"
license: MIT
author: "Joe Vargas"
maintainer: "Joe Vargas"

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - containers
  - safe
  - mtl
  source-dirs: library
  default-extensions:
  - NamedFieldPuns
