# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: lines-of-action
version: '0.0.0'
github: "githubuser/lines-of-action"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: lines-of-action is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - containers
  - safe
  source-dirs: library
  default-extensions:
  - NamedFieldPuns

benchmarks:
  lines-of-action-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - lines-of-action
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  lines-of-action-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - lines-of-action
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
